let gameSinopses = [{game: "hogwarts-legacy", image: "../src/images/hogwarts-legacy.png", sinopse: "Hogwarts Legacy se passa no final do século XIX, ocorrendo em vários locais do mundo mágico, como o castelo de Hogwarts, Hogsmeade e as Terras Altas da Escócia. O jogador assume o papel de um aluno (dublado originalmente por Sebastian Croft ou Amelia Gething) iniciando seus estudos em Hogwarts no quinto ano."},
{game: "watch-dogs", image: "../src/images/watch-dogs.png", sinopse: "A trama de Watch Dogs gira em torno de Aiden Pearce, um homem moldado pela violência e assombrado pelo passado. Após sofrer um atentado juntamente com sua família, uma perda irreparável faz com que o hacker seja impulsionado em uma onda de vingança e justiça. Utilizando o poderoso sistema CtOS que conecta toda a grande Chicago, Aiden utilizará a própria cidade como arma para mudar o sistema corrupto."},
{game: "watch-dogs-2", image: "../src/images/watch-dogs-2.png", sinopse: "Watch_Dogs 2 é ambientado na baía de São Francisco e se desenrola sob a pele de Marcus Holloway, um hacker que foi vítima dos algoritmos de previsão de crime do ctOS 2.0 e acusado injustamente de um delito que não cometeu."},
{game: "dead-cells", image: "../src/images/dead-cells.png", sinopse: "Dead Cells segue a mesma filosofia de Dark Souls em sua história, ou seja, é tudo contado de maneira desconexa, através de suas conversas com NPCs principalmente, e investigando algumas áreas específicas. O jogo oferece mais contexto e ambientação do que um enredo linear em si, com uma história interessante e um tanto original, mas não muito distante do que costumamos ver em games que se inspiram no sucesso da From Software."},
{game: "ghostwire-tokyo", image: "../src/images/ghostwire.png", sinopse: "Em Ghostwire: Tokyo, a cidade japonesa foi tomada por forças sobrenaturais mortais quando um ocultista perigoso fez a população da cidade desaparecer num piscar de olhos. Una suas forças com as de uma poderosa entidade espectral numa busca por vingança e domine um poderoso arsenal de habilidades para descobrir a verdade sombria por trás do desaparecimento enquanto ENCARA O DESCONHECIDO."},
{game: "red-dead-redemption-2", image: "../src/images/red-dead-redemption-2.png", sinopse: "A história se passa em 1899 em uma representação ficcional do oeste, meio-oeste e sul dos Estados Unidos e acompanha o fora da lei Arthur Morgan, que precisa lidar com o declínio do Velho Oeste e sobreviver à perseguição de forças governamentais, gangues rivais e outros adversários."},
{game: "need-for-speed-unbound", image: "../src/images/need-for-speed-unbound.png", sinopse: "A campanha de Need for Speed Unbound traz uma história que serve como pano de fundo para as corridas ilegais da cidade de Lakeshore, um local fictício baseado na cidade de Chicago, nos Estados Unidos. Usuários criam um avatar personalizado que trabalha na oficina Rydell's Rydes, administrada pelo dono Rydell."},
{game: "alan-wake-2", image: "../src/images/alan-wake-2.png", sinopse: "Do que se trata Alan Wake 2? Resolva um Mistério Mortal – O que começa como uma investigação de assassinato em uma cidade pequena rapidamente se transforma em uma jornada de pesadelo. Descubra a fonte da escuridão sobrenatural nesta história de terror psicológico cheia de suspense intenso e reviravoltas inesperadas."},
{game: "dead-island-2", image: "../src/images/dead-island-2.png", sinopse: "Dead Island 2 é um game de ação em primeira pessoa que coloca o jogador em uma Los Angeles isolada depois que uma epidemia transforma a maioria dos moradores em zumbis. A ideia é sobreviver e reunir armas e aliados para sobreviver – e dar o fora dali assim que possível."},
{game: "rage-2", image: "../src/images/rage-2.png", sinopse: "“Rage 2 se passa no mesmo mundo de Rage 1, só que 30 anos depois. A jogabilidade de tiro está ainda melhor desta vez, com armas mais diversas e velozes. Enquanto no primeiro Rage os Nanotrite eram usados para se curar em combate, em Rage 2 eles ajudam a criar novas habilidades incríveis para destruir os inimigos."}]


export{gameSinopses}